{{- if eq .Requirements.webhook "prow" }}
enabled: true
{{- else }}
enabled: false
{{- end }}

hmacToken: "{{ .Parameters.prow.hmacToken }}"
oauthToken: "{{ .Parameters.pipelineUser.token }}"
user: "{{ .Parameters.pipelineUser.username }}"

buildnum:
  enabled: false
pipelinerunner:
  enabled: "true"
  args:
  - controller
  - pipelinerunner
  - --use-meta-pipeline=false
  image:
    repository: gcr.io/jenkinsxio/builder-maven
    tag: 0.1.672
tillerNamespace: ""

sinker:
  replicaCount: 0

pipeline:
  image:
    repository: gcr.io/jenkinsxio/prow/pipeline
    tag: v20190826-3976f61

