{{- if eq .Requirements.webhook "lighthouse" }}
enabled: true
{{- else }}
enabled: false
{{- end }}

hmacToken: "{{ .Parameters.prow.hmacToken }}"

git:
  kind: {{ .Requirements.cluster.gitKind | default "github" }}
  name: {{ .Requirements.cluster.gitName | default "github" }}
  server: {{ .Requirements.cluster.gitServer | default "https://github.com" }}

service:
  name: hook
  
{{- if .Requirements.githubApp.enabled }}
tide:
  githubApp:
    enabled: true

replicaCount: 0
{{- else }}
replicaCount: 1
{{- end }}

image:
  repository: gcr.io/jenkinsxio/lighthouse
